### ISSUE TITLE
Create How to contribute wiki

### ISSUE THREAD

**Issue by SamHuo213** [OpenBCca/openbc-web#31]
Create a Wiki on Contributing to OpenBC-Web

- Reference Setting up project locally
- Reference style Guide
- If part of OpenBC, they should create a branch, create PR when ready
- If part of BC, create a PR to be a code owner. This allows members to review PRs.
- If not part of OpenBC, they should create a fork, create PR when ready
- Branch name should follow features/description
- Reference folder structure

**Comment by alchuu00** [comment]
@Unknown-0perator I have one suggestion regarding 'Contributing Process' section. You could explain a bit that developer grabs a ticket and drags it to 'in progress' and when they make PR they move ticket to 'review' and when it is merged they move it to 'done'. 

Also explain a bit that when developers make PR they should link it to the issue they were working on.

**Comment by alchuu00** [comment]
@Unknown-0perator All good, except if you could explain more about that developer needs to grab a ticket from the board and drag it to 'in progress' and link it to the issue and PR they made. You know what I mean?

**Comment by alchuu00** [comment]
@Unknown-0perator Looks good Ahmad, thank you! 
I will close the issue now.

**Comment by alchuu00** [comment]
@Unknown-0perator Looks good Ahmad, thank you!
I will close the issue now.
