### ISSUE TITLE
Setup Coverage Reports

### ISSUE THREAD

**Issue by SamHuo213** [OpenBCca/openbc-web#35]
Goal
- View coverage metrics (e.g. line coverage %, branch coverage % and etc...)
- Report that shows exactly where the missing coverage is

Task
- Find potential packages we can use (e.g. https://github.com/alexcanessa/typescript-coverage-report, https://istanbul.js.org/ and etc...)
- Update openbc-web to include code coverage reports.
- Create another npm command to run test with coverage reports

**Comment by umsu2** [comment]
we already have the coverage report and current it's set at a low threshold of 30% line to pass the pipeline 
![image](https://github.com/OpenBCca/openbc-web/assets/8355092/408f6d0f-beac-4110-b2fb-7873b00f82dd)
