### ISSUE TITLE
Refactor Header Tabs to Use Prop Value

### ISSUE THREAD

**Issue by SamHuo213** [OpenBCca/openbc-web#40]
Instead of Using CSS to highlight the select tab. We should use the Value prop on Tabs.

![image](https://github.com/OpenBCca/openbc-web/assets/40151580/27ca2b0c-36a7-4734-99e3-97874fa91222)

**Comment by SamHuo213** [comment]
We need to further refactor.

We use Github pages and pre-rendered pages using Next.JS. This means that route information is not available during build time.

This is the cause of failed build.

We should remove the layout and include Header/Footer as part of each page. Pass the route information as a prop to Header.

**Comment by derekd03** [comment]
Move header and other components to be client side, create enum values instead of magic strings
