### ISSUE TITLE
Create footer based on figma design

### ISSUE THREAD

**Issue by nam-m** [OpenBCca/openbc-web#78]
The current footer only contains "OpenBC Sample Text". It should be updated to include social media links, short OpenBC info

Refer to the Figma design [here](https://github.com/OpenBCca/openbc-web/wiki/Project-Info)

**Comment by Unknown-0perator** [comment]
should the footer be exactly like Figma, or do you want something simple for now?

**Comment by nam-m** [comment]
> should the footer be exactly like Figma, or do you want something simple for now?

@Unknown-0perator sorry i missed your comment, yes it should look like Figma. You can exclude the subscription input though since we don't have newsletters. Maybe replacing it with a link to our Linkedin?
Also need to remove some social media links we don't have
