### ISSUE TITLE
Create join us page based on figma design

### ISSUE THREAD

**Issue by nam-m** [OpenBCca/openbc-web#81]
Requirements:
- Present our vision/mission/core values
- Target both volunteers and sponsors
- Reach out to @tokifyi @SherryW14 @Tony-Thawatchai for more info 

Refer to the [Figma design](https://github.com/OpenBCca/openbc-web/wiki/Project-Info) and [SEO plan](https://github.com/OpenBCca/openbc-web/wiki/SEO-Optimization-Plan)

**Comment by PooriaT** [comment]
Integrating email services:

1. [Nodemailer](https://react.email/docs/integrations/nodemailer) => Forwarding
2. [SendGrid](https://react.email/docs/integrations/sendgrid) => Registration required for API Key - Free for 100 emails/day
3. [Postmark](https://react.email/docs/integrations/postmark) => Registration required for API key - Free for 100 emails/month
4. [MailerSend](https://react.email/docs/integrations/mailersend) => Registration required for API key - Free for a total of 3000 emails, $1 per 1000 emails for extra usage.
5. [Resend](https://react.email/docs/integrations/resend) => Registration required - Free for 100 emails/day up to 3000 emails/month
